name: make release

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallelå
jobs:
  directory:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout p1
      uses: actions/checkout@v2
    
    - name: Copycat Directory
      uses: andstor/copycat-action@v3.0.0
      with:
          personal_token: ${{ secrets.PORTFOLIO_SECRET }}
          src_branch: main
          dst_branch: main
          src_path: /.
          dst_path: /.
          dst_owner: josesoaresif
          dst_repo_name: optest
          exclude: _dev/* 


          