name: Copy
on:
  push:
    branches: [ main ]

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        src_path: /.
        dst_path: /.
        dst_owner: josesoaresif
        dst_repo_name: optest.git
        dst_branch: master
        src_branch: master
        src_wiki: true
        dst_wiki: false
        username: josesoaresif
        email: josesoares@ifthenpay.com

